"""empty message

Revision ID: 37007b4ccdac
Revises: b2748d7ddbf9
Create Date: 2018-01-23 23:57:34.705354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37007b4ccdac'
down_revision = 'b2748d7ddbf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket', sa.Column('create_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucket', 'create_at')
    # ### end Alembic commands ###
